### ISSUE TITLE
Some unnecessary Phpdocs

### ISSUE THREAD

**Issue by robinlehrmann** [iota-php/client#15]
Hi, I see some unnecessary phpdocs like @param `classname` over the constructor or other methods but there are already type-hints in the method signature. You should delete all unnecessary php-docs do prevent code redundancy.

**Comment by Techworker** [comment]
Isn't this something that probably php-cs-fixer can fix?

**Comment by Techworker** [comment]
Can you contact me on slack / discord?

**Comment by robinlehrmann** [comment]
Yes, I think, that can be done by php-cs-fixer.
