### ISSUE TITLE
Prefer to use HTTP Plug to implement PSR-7 Standard

### ISSUE THREAD

**Issue by robinlehrmann** [iota-php/client#16]
I see in this class https://github.com/Techworker/iota-php/blob/master/src/RemoteApi/HttpClient/GuzzleClient.php you want to interface a http adapter logic. I think for that would be http-plug the much better solution. Check this out: https://github.com/php-http/httplug
If you want I would implement it :)

**Comment by Techworker** [comment]
Just a note: 

We need the possibility to send sync and async requests - async is not implemented right now but will be needed asap. Especially the bundle retrieval is a pain in the ass right now.

**Comment by robinlehrmann** [comment]
That can be done with http-plug. We can have a look at this later this day.
