### ISSUE TITLE
create vagrant devbox with ansible provision for a generic dev environment

### ISSUE THREAD

**Issue by robinlehrmann** [iota-php/client#17]
I would prefer to use vagrant with ansible to have a development environment, that automatically provisioning the required php packages and some else dependencies.

**Comment by Techworker** [comment]
My problem with it is that I cannot support it in any way in case there will be an issue. And it's not related to the project per se.

If you will commit yourself to support it, I'm fine, but from my POV the requirements in the composer.json should be enough (https://github.com/Techworker/iota-php/blob/master/composer.json#L30-L31).

I was also thinking about removing the `.docker` folder, but if you think this (and your recommendation) is helpful for the developer community I'm fine.

Would it make sense to create a dedicated repository for that?

**Comment by robinlehrmann** [comment]
I agree with your suggestion to create a dedicated repository. I will create it a.s.a.p. and yes, we should remove the .docker directory

**Comment by robinlehrmann** [comment]
https://github.com/robinlehrmann/php-7.2-devbox
I've created a devbox with minimum requirements. It's debian as distribution. We can remove th e docker directory. 
Maybe we should link it in the docs, what do you think?

**Comment by robinlehrmann** [comment]
I think we can close it, because I've create a devbox in the iota-php group.
