### ISSUE TITLE
Docs creation with sphinx

### ISSUE THREAD

**Issue by robinlehrmann** [iota-php/client#18]
We should take a look at this: https://www.sitepoint.com/using-sphinx-for-php-project-documentation/

I think we shouldn't create our own logic for it.

**Comment by Techworker** [comment]
Would love to have that!

**Comment by Techworker** [comment]
No significant progress in 8 months, will close this for now. We need documentation first before we could even think of sth. like that, and also probably readme.io is better suited with less technical dependencies.
