### ISSUE TITLE
PHP Keccak Lib

### ISSUE THREAD

**Issue by KuLi** [iota-php/client#2]
It would be nice, if you use a native library  for Keccak. 
There ist one https://github.com/kornrunner/php-keccak.

If you have no time, i would implement it for you if you want.

**Comment by Techworker** [comment]
I'll check it out, I tried a lot but sadly keccak384 !== sha3-384

**Comment by Techworker** [comment]
Implemented, thanks a lot!

See https://github.com/Techworker/iota-php/commit/fe71b7263dc822447d6673243061af3a557ec629
