### ISSUE TITLE
CCurl for travis

### ISSUE THREAD

**Issue by Techworker** [iota-php/client#39]
The Kerl tests fail on travis because there is no ccurl (doing POW) available - we'll need that to test against the existing test-vectors provided by iota.

We either need to download a pre-compiled ccurl or compile it directly on travis with each test - I'm for the former.

Project is here: https://github.com/iotaledger/ccurl

**Comment by peter279k** [comment]
According to the [kerl,js](https://github.com/iotaledger/iota.js/blob/develop/lib/crypto/kerl/kerl.js) and .[travis.yml](https://github.com/iotaledger/iota.js/blob/develop/.travis.yml) in the`iota.js`, it seems that it doesn't have to add the `CCurl` library.

Perhaps we have to search the real issue deeply about the `Kerl` works :+1: .
I guess we should check whether the `Kerl` implementation is correct.

**Comment by Techworker** [comment]
They are using the JS implementation to calculate the POW. We don't have one in PHP, as it is very resource intensive and cannot be ported efficiently (well, maybe someone can, I don't or better I won't). It uses either the GPU, multithreading and so on.

I would retain from adding ccurl at all and just mock POW results in the tests as we will not calculate the POW on travis. So essentially, this issue can be closed.

Ok?

**Comment by peter279k** [comment]
@Techworker, thank you for your reply. It looks like we have the one of work to solve this issue.

- Using the `CCurl` to mock POW results.
- Implement the `Kerl` correctly and let this pass the unit test in Travis CI build.

Do you refer this [PR](https://github.com/iotaledger/kerl/pull/4)? I think we can try it out :+1: .

**Comment by Techworker** [comment]
Well, my Kerl implementation does work, no need to change it or use another one. 

What is missing (PHP wise) is the function that does the Proof of work when calling `attachToTangle`, because if the node does not support doing the POW, you'll have to do it locally. And thats what we do with ccurl, as it would be inefficient to do the POW in PHP.

But with the recent additions of remote POW endpoints for IOTA, so that even smaller devices can make transactions (by letting others do the POW), we do not necessarily need to port this functionality and just use an optimized ccurl executable in case there is no remote endpoint available.

But back to this issue: we don't need to do the POW in tests, so we don't need it on travis, as it does not make any sense for us.

The current implementation of the POWInterface should be sufficient:
https://github.com/iota-php/client/blob/master/src/Cryptography/POW/CCurl.php

**Comment by peter279k** [comment]
@Techworker, thank you for your explanation. So the work is updated:

We have to build the `CCurl` and use this to calculate/mock the POW result.

I don't think we have to build this for every oncoming Travis CI builds and it will let CI work quickly.

Perhaps we have to consider [this](https://github.com/iotaledger/ccurl/releases) and it also provides the pre-compiled `CCurl` dynamic link library in every released version. How about downloading this directly in Travis CI build?

**Comment by Techworker** [comment]
No, we don't need ccurl at all on travis, thats what I wanted to say. Everything that ccurl would do and its results when calling it can be mocked in the tests. We do not test ccurl, because we cannot verify it, so we remove it completely from the tests and will not depend on this executable when executing the tests.

**Comment by Techworker** [comment]
We just use it like this:

```php
$powMock = $this->createMock(PowInterface::class);
$powMock->method('execute')
	->willReturn('SOME_RANDOM_TRYTES');
```

.. in our tests and we are fine. No need to do heavy calculations we cannot predict on travis, as the calculation is not done in our code.

**Comment by peter279k** [comment]
Ok. I understand now, but why the label is `bug`? It lets me misunderstand I think :confused: .

**Comment by Techworker** [comment]
yeah, probably an error, sorry for that. Repo is a bit abandoned, but now you are here and bring in some activity ;-)

**Comment by peter279k** [comment]
I think this issue should be reopened and I know using the PPHUnit `Mock` API to mock this POW results.

Perhaps we can create another issue and let that issue tag the `enhancement` to remind us that work should be mocked by the PHPUnit Mock 😃.
