### ISSUE TITLE
Using the one of extension to process the big number

### ISSUE THREAD

**Issue by peter279k** [iota-php/client#52]
As title, this PHP package uses the `BCMath` and `GMP` extensions to process the big numbers.

I think it's not necessary to use two extensions for doing the same work.

Perhaps we can only use the `GMP` extension to handle this because the `GMP` extension function support is large than `BCMath`. I think the `bc_*` functions can be replaced with the `gmp_*` functions.

This will be maintained easily because it has only a `GMP` extension and we just focus on this extension :+1: .

**Comment by Techworker** [comment]
You are right, one is enough. The `/src/Type/Iota.php` Type should be simple to port to GMP (I think this is the only one using bc* functions)

**Comment by peter279k** [comment]
Hi @Techworker, after researching the `GMP` functions, I found some `BCMath` functions cannot really replace with `GMP` functions.

For example, the `bc_div` function is different from the `gmp_div_q`. You can see more details about that on [official PHP doc](http://php.net/manual/en/function.gmp-div-q.php).

It looks like the `BCMath` can calculate the floating numbers directly, and the `GMP` only can calculate the big integers.

Perhaps I think it's fine to keep the `src/Type/Iota.php` using the `BCMath` funtions.

This issue is also closed.
