### ISSUE TITLE
The condition in TritsUtil::fromInt static method is strange

### ISSUE THREAD

**Issue by peter279k** [iota-php/client#56]
As title, The condition in `IOTA\Util\TritsUtil::fromInt` static method is strange.

Consider the following code snippets:

```php
public static function fromInt(string $int, int $hashLength): array
 {
        $trits = [];
        if (\is_int($int)) { ... }
        ...
}
```

This `is_int` condition will not be triggered because the `$int` type hint is `string`.

And the `declare(strict_types=1);` is defined in the begining of this PHP file.

If we pass the `integer` type of `$int`, it will throw the fatal `TypeError` exception.

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to TritsUtil::fromInt() must be of the type string, integer given
```
The correct way is: Removing the `$int` type hint if we want to trigger the `if (\is_int($int))` condition block :+1: .

BTW, I'm not sure this related issue happen on other classes for this repo.

**Comment by Techworker** [comment]
Hi @peter279k,

Indeed, this looks suspicious and the condition will never be true. I forgot why I did that, ported it from somewhere and then changed the method signature to string somewhere in the middle of development.

I think we can remove the is_int() condition as well as the code that would have been triggered.

Or, if you are not 100% sure what it does, just leave it like it is for now and wait until someone will write tests for the functionality.

**Comment by peter279k** [comment]
@Techworker, thank you for your quick reply. There're two works need to be done.

- Removing the `is_int` condition block.
- Adding the related unit tests for this.

**Comment by peter279k** [comment]
BTW, it seems that you ported this from old `iota.js` and it is for the `develop` branch :+1:.

It's in the [lib/crypto/converter/converter.js](https://github.com/iotaledger/iota.js/blob/develop/lib/crypto/converter/converter.js#L55).

```JS
var trits = function( input, state ) {

    var trits = state || [];

    if (Number.isInteger(input)) {

        var absoluteValue = input < 0 ? -input : input;

        while (absoluteValue > 0) {

            var remainder = absoluteValue % 3;
            absoluteValue = Math.floor(absoluteValue / 3);

            if (remainder > 1) {
                remainder = -1;
                absoluteValue++;
            }
...
```

**Comment by Techworker** [comment]
Essentially it will never be an int, so it can go.
