### ISSUE TITLE
IOTA\Util\TryteUtil::toTrits should check the key is existed

### ISSUE THREAD

**Issue by peter279k** [iota-php/client#59]
Consider the static method `toTrits` approach:

```php
public static function toTrits(string $tryte): array
{
    return self::TRYTE_TO_TRITS_MAP[$tryte];
}
```

This is the public static method and we can call this from this class instance.

We have to check whether `$tryte` key is existed in the `TRYTE_TO_TRITS_MAP` array.

I think we can consider the following approach to solve that:

```php
    /**
     * Creates a new Tryte from the given 3 trits.
     *
     * @param string $tryte
     *
     * @return null|int[]
     */
    public static function toTrits(string $tryte): array
    {
        return self::TRYTE_TO_TRITS_MAP[$tryte] ?? null;
    }
```

**Comment by peter279k** [comment]
Another approach is: throw the `\InvalidArgumentException` directly.

**Comment by Techworker** [comment]
I prefer throwing an exception in that case. If it returns null it might lead to follow up errors which are then hard to debug.

If you send an invalid tryte, sth. Is really wrong somewhere else.

**Comment by Techworker** [comment]
Merged, thanks!
