### ISSUE TITLE
Missing isAddress in IOTA\Util\AddressUtil class

### ISSUE THREAD

**Issue by peter279k** [iota-php/client#63]
As title, I think it should add this method to validate the address format.

And it can see more detailed unit test from [this](https://github.com/iotaledger/iota.js/blob/develop/test/valid/valid.isAddress.js).

**Comment by Techworker** [comment]
As mentioned [here](https://github.com/iota-php/client/issues/54#issuecomment-415547775), the validation is done in the constructor of the corresponding value type.

**Comment by peter279k** [comment]
I'm sorry about that I forgot :cry: .
